mode = "client"
# protocol_dir is deprecated - protocols are now embedded in the binary

[encryption]
cipher = "cha-cha20-poly1305"
key_derivation = "argon2"
password = "nooshdaroo-client-secret"

[shapeshift.strategy]
type = "fixed"
protocol = "dns"

[socks]
listen_addr = "127.0.0.1:1080"
server_address = "23.128.36.102:53"
auth_required = false

[transport]
pattern = "nk"
remote_public_key = "4wIWM/RDNNY1GhBqK3eLgFBznWzq7RIhaPwhUy9Cpn8="
