mode = "client"
protocol_dir = "protocols"

[encryption]
cipher = "cha-cha20-poly1305"
key_derivation = "argon2"
password = "nooshdaroo-client-secret"

[shapeshift.strategy]
type = "fixed"
protocol = "https"

[socks]
listen_addr = "127.0.0.1:1080"
server_address = "23.128.36.42:8443"
auth_required = false

[transport]
pattern = "nk"
remote_public_key = "4wIWM/RDNNY1GhBqK3eLgFBznWzq7RIhaPwhUy9Cpn8="
