mode = "server"
protocol_dir = "protocols"

[encryption]
cipher = "cha-cha20-poly1305"
key_derivation = "argon2"
password = "nooshdaroo-server-secret"

[shapeshift.strategy]
type = "fixed"
protocol = "https"

[server]
listen_addr = "0.0.0.0:8443"
forward_addr = "127.0.0.1:80"
forward_proto = "tcp"

[transport]
pattern = "nk"
local_private_key = "T1ncZuk3c4c7ewdgd/gHLAJgsH3MJCLltvbLuxxz1lk="
