mode = "server"

[encryption]
cipher = "cha-cha20-poly1305"
key_derivation = "argon2"
password = "nooshdaroo-local-test"

[shapeshift.strategy]
type = "fixed"
protocol = "https"

[server]
listen_addr = "127.0.0.1:8443"

[transport]
pattern = "nk"
local_private_key = "5cxpzw1sBSmGFXVzUT6xV4gh8hlhlSVwWB8W1wSIMRI="
